[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello-world"
path = "src/hello-world/main.rs"

[[bin]]
name = "guess-number"
path = "src/guess-number/main.rs"

[dependencies]
rand = "0.8.5"
